name: keyboard_visibility_example
description: Keyboard visibility example

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_visibility:
    path: ../

flutter:
  uses-material-design: true
