name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 0.5.6
author: adee42 <42adee@gmail.com>
homepage: https://github.com/adee42/flutter_keyboard_visibility/tree/master

environment:
  sdk: ">=2.13.0 <4.0.0"
  flutter: ">=2.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.github.adee42.keyboardvisibility
    iosPrefix: FLT
    pluginClass: KeyboardVisibilityPlugin
